window.CATALOG_DATA = [
  {
    "id": "flora",
    "name": "Flora",
    "material": "Velvet",
    "category": "Sofa Upholstery",
    "tag": "Signature",
    "composition": "100% Polyester",
    "rubLabel": "Rub Count",
    "rub": "20,000 Martindale",
    "gsm": 425,
    "care": "Machine washable up to 40°C. Do not bleach, iron, or tumble dry. Professional dry cleaning permitted.",
    "application": "Sofa Upholstery, Curtains & Drapery",
    "heroImage": "./assets/sofa/flora/hero.jpg",
    "widthCm": 140,
    "mrp": 590,
    "gstRate": 5,
    "hsnCode": "6005",
    "swatches": [
      { "name": "SR 01", "code": "FL-01", "hex": "#ece1d1", "img": "./assets/sofa/flora/swatches/FL-01.jpg" },
      { "name": "SR 02", "code": "FL-02", "hex": "#dedad4", "img": "./assets/sofa/flora/swatches/FL-02.jpg" },
      { "name": "SR 03", "code": "FL-03", "hex": "#bfb6ad", "img": "./assets/sofa/flora/swatches/FL-03.jpg" },
      { "name": "SR 04", "code": "FL-04", "hex": "#d7c8b0", "img": "./assets/sofa/flora/swatches/FL-04.jpg" },
      { "name": "SR 05", "code": "FL-05", "hex": "#d1ad81", "img": "./assets/sofa/flora/swatches/FL-05.jpg" },
      { "name": "SR 06", "code": "FL-06", "hex": "#a58d76", "img": "./assets/sofa/flora/swatches/FL-06.jpg" },
      { "name": "SR 07", "code": "FL-07", "hex": "#ad7c48", "img": "./assets/sofa/flora/swatches/FL-07.jpg" },
      { "name": "SR 08", "code": "FL-08", "hex": "#83827e", "img": "./assets/sofa/flora/swatches/FL-08.jpg" },
      { "name": "SR 09", "code": "FL-09", "hex": "#867f78", "img": "./assets/sofa/flora/swatches/FL-09.jpg" },
      { "name": "SR 10", "code": "FL-10", "hex": "#8bab94", "img": "./assets/sofa/flora/swatches/FL-10.jpg" },
      { "name": "SR 11", "code": "FL-11", "hex": "#047487", "img": "./assets/sofa/flora/swatches/FL-11.jpg" },
      { "name": "SR 12", "code": "FL-12", "hex": "#057276", "img": "./assets/sofa/flora/swatches/FL-12.jpg" },
      { "name": "SR 13", "code": "FL-13", "hex": "#035f48", "img": "./assets/sofa/flora/swatches/FL-13.jpg" },
      { "name": "SR 14", "code": "FL-14", "hex": "#a0afb4", "img": "./assets/sofa/flora/swatches/FL-14.jpg" },
      { "name": "SR 15", "code": "FL-15", "hex": "#096b97", "img": "./assets/sofa/flora/swatches/FL-15.jpg" },
      { "name": "SR 16", "code": "FL-16", "hex": "#0491a8", "img": "./assets/sofa/flora/swatches/FL-16.jpg" },
      { "name": "SR 17", "code": "FL-17", "hex": "#397d9a", "img": "./assets/sofa/flora/swatches/FL-17.jpg" },
      { "name": "SR 18", "code": "FL-18", "hex": "#093e72", "img": "./assets/sofa/flora/swatches/FL-18.jpg" },
      { "name": "SR 19", "code": "FL-19", "hex": "#d2a92e", "img": "./assets/sofa/flora/swatches/FL-19.jpg" },
      { "name": "SR 20", "code": "FL-20", "hex": "#be8b81", "img": "./assets/sofa/flora/swatches/FL-20.jpg" },
      { "name": "SR 21", "code": "FL-21", "hex": "#af6057", "img": "./assets/sofa/flora/swatches/FL-21.jpg" }
    ]
  },
  {
    "id": "florida",
    "name": "Florida",
    "material": "Textured Weave",
    "category": "Sofa Upholstery",
    "tag": null,
    "composition": "100% Polyester",
    "rubLabel": "Rub Count",
    "rub": "30,000 Martindale",
    "gsm": 400,
    "care": "Machine washable up to 40°C. Do not bleach. Do not iron. Do not tumble dry. Professional dry cleaning (hydrocarbon solvent) permitted.",
    "application": "Sofa Upholstery",
    "heroImage": "./assets/sofa/florida/hero.jpg",
    "widthCm": 140,
    "mrp": 670,
    "gstRate": 5,
    "hsnCode": "6005",
    "swatches": [
      { "name": "SR 801", "code": "FD-801", "hex": "#ddcdba", "img": "./assets/sofa/florida/swatches/FD-801.jpg" },
      { "name": "SR 802", "code": "FD-802", "hex": "#ddc9af", "img": "./assets/sofa/florida/swatches/FD-802.jpg" },
      { "name": "SR 803", "code": "FD-803", "hex": "#ddb596", "img": "./assets/sofa/florida/swatches/FD-803.jpg" },
      { "name": "SR 804", "code": "FD-804", "hex": "#cfaf8e", "img": "./assets/sofa/florida/swatches/FD-804.jpg" },
      { "name": "SR 805", "code": "FD-805", "hex": "#a5734a", "img": "./assets/sofa/florida/swatches/FD-805.jpg" },
      { "name": "SR 806", "code": "FD-806", "hex": "#a15e31", "img": "./assets/sofa/florida/swatches/FD-806.jpg" },
      { "name": "SR 807", "code": "FD-807", "hex": "#cb9969", "img": "./assets/sofa/florida/swatches/FD-807.jpg" },
      { "name": "SR 808", "code": "FD-808", "hex": "#6c4b32", "img": "./assets/sofa/florida/swatches/FD-808.jpg" },
      { "name": "SR 809", "code": "FD-809", "hex": "#613622", "img": "./assets/sofa/florida/swatches/FD-809.jpg" },
      { "name": "SR 810", "code": "FD-810", "hex": "#834c33", "img": "./assets/sofa/florida/swatches/FD-810.jpg" },
      { "name": "SR 811", "code": "FD-811", "hex": "#cc846a", "img": "./assets/sofa/florida/swatches/FD-811.jpg" },
      { "name": "SR 812", "code": "FD-812", "hex": "#b26059", "img": "./assets/sofa/florida/swatches/FD-812.jpg" },
      { "name": "SR 813", "code": "FD-813", "hex": "#517b5d", "img": "./assets/sofa/florida/swatches/FD-813.jpg" },
      { "name": "SR 814", "code": "FD-814", "hex": "#a59787", "img": "./assets/sofa/florida/swatches/FD-814.jpg" },
      { "name": "SR 815", "code": "FD-815", "hex": "#467064", "img": "./assets/sofa/florida/swatches/FD-815.jpg" },
      { "name": "SR 816", "code": "FD-816", "hex": "#286771", "img": "./assets/sofa/florida/swatches/FD-816.jpg" },
      { "name": "SR 817", "code": "FD-817", "hex": "#578691", "img": "./assets/sofa/florida/swatches/FD-817.jpg" },
      { "name": "SR 818", "code": "FD-818", "hex": "#3f5f69", "img": "./assets/sofa/florida/swatches/FD-818.jpg" },
      { "name": "SR 819", "code": "FD-819", "hex": "#968d83", "img": "./assets/sofa/florida/swatches/FD-819.jpg" },
      { "name": "SR 820", "code": "FD-820", "hex": "#8f6e6a", "img": "./assets/sofa/florida/swatches/FD-820.jpg" },
      { "name": "SR 821", "code": "FD-821", "hex": "#948b81", "img": "./assets/sofa/florida/swatches/FD-821.jpg" }
    ]
  },
  {
    "id": "salute",
    "name": "Salute",
    "material": "Leatherette",
    "category": "Sofa Upholstery",
    "tag": null,
    "composition": "4% PU, 71% PVC, 25% Fabric",
    "rubLabel": "Rub Count",
    "rub": "120,000 Martindale",
    "gsm": 550,
    "care": "Machine washable up to 40°C. Do not bleach. Do not iron. Do not tumble dry. Professional dry cleaning (P – perchloroethylene solvent) permitted.",
    "application": "Sofa Upholstery",
    "heroImage": "./assets/sofa/salute/hero.jpg",
    "widthCm": 140,
    "mrp": 870,
    "gstRate": 5,
    "hsnCode": "5903",
    "swatches": [
      { "name": "SR 601", "code": "SL-601", "hex": "#bfb6ad", "img": "./assets/sofa/salute/swatches/SL-601.jpg" },
      { "name": "SR 602", "code": "SL-602", "hex": "#9a968b", "img": "./assets/sofa/salute/swatches/SL-602.jpg" },
      { "name": "SR 603", "code": "SL-603", "hex": "#918a81", "img": "./assets/sofa/salute/swatches/SL-603.jpg" },
      { "name": "SR 604", "code": "SL-604", "hex": "#f7e6d7", "img": "./assets/sofa/salute/swatches/SL-604.jpg" },
      { "name": "SR 605", "code": "SL-605", "hex": "#b5a598", "img": "./assets/sofa/salute/swatches/SL-605.jpg" },
      { "name": "SR 606", "code": "SL-606", "hex": "#ab988c", "img": "./assets/sofa/salute/swatches/SL-606.jpg" },
      { "name": "SR 607", "code": "SL-607", "hex": "#f6f7f5", "img": "./assets/sofa/salute/swatches/SL-607.jpg" },
      { "name": "SR 608", "code": "SL-608", "hex": "#fdf9ee", "img": "./assets/sofa/salute/swatches/SL-608.jpg" },
      { "name": "SR 609", "code": "SL-609", "hex": "#efdabd", "img": "./assets/sofa/salute/swatches/SL-609.jpg" },
      { "name": "SR 610", "code": "SL-610", "hex": "#dcc3a6", "img": "./assets/sofa/salute/swatches/SL-610.jpg" },
      { "name": "SR 611", "code": "SL-611", "hex": "#bd8f6d", "img": "./assets/sofa/salute/swatches/SL-611.jpg" },
      { "name": "SR 612", "code": "SL-612", "hex": "#ad8667", "img": "./assets/sofa/salute/swatches/SL-612.jpg" },
      { "name": "SR 613", "code": "SL-613", "hex": "#9d877c", "img": "./assets/sofa/salute/swatches/SL-613.jpg" },
      { "name": "SR 614", "code": "SL-614", "hex": "#ede5d7", "img": "./assets/sofa/salute/swatches/SL-614.jpg" },
      { "name": "SR 615", "code": "SL-615", "hex": "#a4a097", "img": "./assets/sofa/salute/swatches/SL-615.jpg" },
      { "name": "SR 616", "code": "SL-616", "hex": "#b9b3a7", "img": "./assets/sofa/salute/swatches/SL-616.jpg" },
      { "name": "SR 617", "code": "SL-617", "hex": "#e1dac8", "img": "./assets/sofa/salute/swatches/SL-617.jpg" },
      { "name": "SR 618", "code": "SL-618", "hex": "#f6cbc2", "img": "./assets/sofa/salute/swatches/SL-618.jpg" },
      { "name": "SR 619", "code": "SL-619", "hex": "#d2cfc6", "img": "./assets/sofa/salute/swatches/SL-619.jpg" },
      { "name": "SR 620", "code": "SL-620", "hex": "#8b8d82", "img": "./assets/sofa/salute/swatches/SL-620.jpg" },
      { "name": "SR 621", "code": "SL-621", "hex": "#8c9383", "img": "./assets/sofa/salute/swatches/SL-621.jpg" },
      { "name": "SR 622", "code": "SL-622", "hex": "#77827a", "img": "./assets/sofa/salute/swatches/SL-622.jpg" },
      { "name": "SR 623", "code": "SL-623", "hex": "#c88356", "img": "./assets/sofa/salute/swatches/SL-623.jpg" },
      { "name": "SR 624", "code": "SL-624", "hex": "#a57664", "img": "./assets/sofa/salute/swatches/SL-624.jpg" },
      { "name": "SR 625", "code": "SL-625", "hex": "#8a6961", "img": "./assets/sofa/salute/swatches/SL-625.jpg" },
      { "name": "SR 626", "code": "SL-626", "hex": "#9b9891", "img": "./assets/sofa/salute/swatches/SL-626.jpg" },
      { "name": "SR 627", "code": "SL-627", "hex": "#716c66", "img": "./assets/sofa/salute/swatches/SL-627.jpg" }
    ]
  },
  {
    "id": "ankara",
    "name": "Ankara",
    "material": "Boucle Weave",
    "category": "Sofa Upholstery",
    "tag": null,
    "composition": "100% Polyester",
    "rubLabel": "Rub Count",
    "rub": "40,000 Martindale",
    "gsm": 425,
    "care": "Machine washable up to 40°C. Do not bleach. Do not iron. Do not tumble dry. Professional dry cleaning (P – perchloroethylene solvent) permitted.",
    "application": "Sofa Upholstery",
    "heroImage": "./assets/sofa/ankara/hero.jpg",
    "widthCm": 140,
    "mrp": 790,
    "gstRate": 5,
    "hsnCode": "6001",
    "swatches": [
      { "name": "SR 01", "code": "AK-01", "hex": "#c9bba6", "img": "./assets/sofa/ankara/swatches/AK-01.jpg" },
      { "name": "SR 02", "code": "AK-02", "hex": "#c0ad93", "img": "./assets/sofa/ankara/swatches/AK-02.jpg" },
      { "name": "SR 03", "code": "AK-03", "hex": "#baa588", "img": "./assets/sofa/ankara/swatches/AK-03.jpg" },
      { "name": "SR 04", "code": "AK-04", "hex": "#9e8871", "img": "./assets/sofa/ankara/swatches/AK-04.jpg" },
      { "name": "SR 05", "code": "AK-05", "hex": "#968579", "img": "./assets/sofa/ankara/swatches/AK-05.jpg" },
      { "name": "SR 06", "code": "AK-06", "hex": "#8b8374", "img": "./assets/sofa/ankara/swatches/AK-06.jpg" },
      { "name": "SR 07", "code": "AK-07", "hex": "#bc8979", "img": "./assets/sofa/ankara/swatches/AK-07.jpg" },
      { "name": "SR 08", "code": "AK-08", "hex": "#8e3f42", "img": "./assets/sofa/ankara/swatches/AK-08.jpg" },
      { "name": "SR 09", "code": "AK-09", "hex": "#b03914", "img": "./assets/sofa/ankara/swatches/AK-09.jpg" },
      { "name": "SR 10", "code": "AK-10", "hex": "#918257", "img": "./assets/sofa/ankara/swatches/AK-10.jpg" },
      { "name": "SR 11", "code": "AK-11", "hex": "#514e2b", "img": "./assets/sofa/ankara/swatches/AK-11.jpg" },
      { "name": "SR 12", "code": "AK-12", "hex": "#284032", "img": "./assets/sofa/ankara/swatches/AK-12.jpg" },
      { "name": "SR 13", "code": "AK-13", "hex": "#73767e", "img": "./assets/sofa/ankara/swatches/AK-13.jpg" },
      { "name": "SR 14", "code": "AK-14", "hex": "#a89e95", "img": "./assets/sofa/ankara/swatches/AK-14.jpg" },
      { "name": "SR 15", "code": "AK-15", "hex": "#a6988e", "img": "./assets/sofa/ankara/swatches/AK-15.jpg" },
      { "name": "SR 16", "code": "AK-16", "hex": "#8c8077", "img": "./assets/sofa/ankara/swatches/AK-16.jpg" },
      { "name": "SR 17", "code": "AK-17", "hex": "#717671", "img": "./assets/sofa/ankara/swatches/AK-17.jpg" },
      { "name": "SR 18", "code": "AK-18", "hex": "#22262d", "img": "./assets/sofa/ankara/swatches/AK-18.jpg" }
    ]
  },
  {
    "id": "athens",
    "name": "Athens",
    "material": "Printed Velvet",
    "category": "Sofa Upholstery",
    "tag": null,
    "composition": "100% Polyester",
    "rubLabel": "Rub Count",
    "rub": "40,000 Martindale",
    "gsm": 425,
    "care": "Machine washable up to 40°C. Do not bleach. Do not iron. Do not tumble dry. Professional dry cleaning (P – perchloroethylene solvent) permitted.",
    "application": "Sofa Upholstery",
    "widthCm": 140,
    "heroImage": "./assets/sofa/athens/hero.jpg",
    "mrp": 790,
    "gstRate": 5,
    "hsnCode": "6005",
    "swatches": [
      { "name": "SR 201", "code": "AT-201", "hex": "#b09384", "img": "./assets/sofa/athens/swatches/AT-201.jpg" },
      { "name": "SR 202", "code": "AT-202", "hex": "#9c7360", "img": "./assets/sofa/athens/swatches/AT-202.jpg" },
      { "name": "SR 203", "code": "AT-203", "hex": "#856350", "img": "./assets/sofa/athens/swatches/AT-203.jpg" },
      { "name": "SR 205", "code": "AT-205", "hex": "#e8d2bc", "img": "./assets/sofa/athens/swatches/AT-205.jpg" },
      { "name": "SR 206", "code": "AT-206", "hex": "#baa294", "img": "./assets/sofa/athens/swatches/AT-206.jpg" },
      { "name": "SR 207", "code": "AT-207", "hex": "#9c928a", "img": "./assets/sofa/athens/swatches/AT-207.jpg" },
      { "name": "SR 208", "code": "AT-208", "hex": "#7e7875", "img": "./assets/sofa/athens/swatches/AT-208.jpg" },
      { "name": "SR 209", "code": "AT-209", "hex": "#5d5b57", "img": "./assets/sofa/athens/swatches/AT-209.jpg" },
      { "name": "SR 210", "code": "AT-210", "hex": "#516f5d", "img": "./assets/sofa/athens/swatches/AT-210.jpg" },
      { "name": "SR 211", "code": "AT-211", "hex": "#717e76", "img": "./assets/sofa/athens/swatches/AT-211.jpg" },
      { "name": "SR 212", "code": "AT-212", "hex": "#476469", "img": "./assets/sofa/athens/swatches/AT-212.jpg" },
      { "name": "SR 214", "code": "AT-214", "hex": "#80463b", "img": "./assets/sofa/athens/swatches/AT-214.jpg" },
      { "name": "SR 215", "code": "AT-215", "hex": "#c1764a", "img": "./assets/sofa/athens/swatches/AT-215.jpg" },
      { "name": "SR 216", "code": "AT-216", "hex": "#974212", "img": "./assets/sofa/athens/swatches/AT-216.jpg" }
    ]
  },
  {
    "id": "wonder",
    "name": "Wonder",
    "material": "Textured Weave",
    "category": "Sofa Upholstery",
    "tag": null,
    "composition": "100% Polyester",
    "rubLabel": "Rub Count",
    "rub": "32,000 Martindale",
    "gsm": 350,
    "care": "Machine washable up to 40°C. Do not bleach. Do not iron. Do not tumble dry. Professional dry cleaning (P – perchloroethylene solvent) permitted.",
    "application": "Sofa Upholstery",
    "widthCm": 140,
    "heroImage": "./assets/sofa/wonder/hero.jpg",
    "mrp": 750,
    "gstRate": 5,
    "hsnCode": "6005",
    "swatches": [
      { "name": "SR 01", "code": "WD-01", "hex": "#d5bdaa", "img": "./assets/sofa/wonder/swatches/WD-01.jpg" },
      { "name": "SR 02", "code": "WD-02", "hex": "#d0bba7", "img": "./assets/sofa/wonder/swatches/WD-02.jpg" },
      { "name": "SR 03", "code": "WD-03", "hex": "#f7eac7", "img": "./assets/sofa/wonder/swatches/WD-03.jpg" },
      { "name": "SR 04", "code": "WD-04", "hex": "#8f745d", "img": "./assets/sofa/wonder/swatches/WD-04.jpg" },
      { "name": "SR 05", "code": "WD-05", "hex": "#624f46", "img": "./assets/sofa/wonder/swatches/WD-05.jpg" },
      { "name": "SR 06", "code": "WD-06", "hex": "#b0663d", "img": "./assets/sofa/wonder/swatches/WD-06.jpg" },
      { "name": "SR 07", "code": "WD-07", "hex": "#93988e", "img": "./assets/sofa/wonder/swatches/WD-07.jpg" },
      { "name": "SR 08", "code": "WD-08", "hex": "#606d6c", "img": "./assets/sofa/wonder/swatches/WD-08.jpg" },
      { "name": "SR 09", "code": "WD-09", "hex": "#4b5258", "img": "./assets/sofa/wonder/swatches/WD-09.jpg" },
      { "name": "SR 10", "code": "WD-10", "hex": "#b4a89e", "img": "./assets/sofa/wonder/swatches/WD-10.jpg" },
      { "name": "SR 11", "code": "WD-11", "hex": "#736967", "img": "./assets/sofa/wonder/swatches/WD-11.jpg" }
    ]
  },
  {
    "id": "malabar",
    "name": "Malabar",
    "material": "Jacquard Weave",
    "category": "Sofa Upholstery",
    "tag": null,
    "composition": "100% Polyester",
    "rubLabel": "Rub Count",
    "rub": "20,000 Martindale",
    "gsm": 440,
    "care": "Machine washable up to 40°C. Do not bleach. Do not iron. Do not tumble dry. Professional dry cleaning (P – perchloroethylene solvent) permitted.",
    "application": "Sofa Upholstery",
    "widthCm": 140,
    "heroImage": "./assets/sofa/malabar/hero.jpg",
    "mrp": 844,
    "gstRate": 5,
    "hsnCode": "6005",
    "swatches": [
      { "name": "SR 801", "code": "MB-801", "hex": "#dfb376", "img": "./assets/sofa/malabar/swatches/MB-801.jpg" },
      { "name": "SR 802", "code": "MB-802", "hex": "#d8beaf", "img": "./assets/sofa/malabar/swatches/MB-802.jpg" },
      { "name": "SR 804", "code": "MB-804", "hex": "#cc917e", "img": "./assets/sofa/malabar/swatches/MB-804.jpg" },
      { "name": "SR 807", "code": "MB-807", "hex": "#d5b39c", "img": "./assets/sofa/malabar/swatches/MB-807.jpg" },
      { "name": "SR 808", "code": "MB-808", "hex": "#c7ac97", "img": "./assets/sofa/malabar/swatches/MB-808.jpg" },
      { "name": "SR 810", "code": "MB-810", "hex": "#c5ae97", "img": "./assets/sofa/malabar/swatches/MB-810.jpg" },
      { "name": "SR 811", "code": "MB-811", "hex": "#ae8556", "img": "./assets/sofa/malabar/swatches/MB-811.jpg" },
      { "name": "SR 812", "code": "MB-812", "hex": "#a26a45", "img": "./assets/sofa/malabar/swatches/MB-812.jpg" },
      { "name": "SR 814", "code": "MB-814", "hex": "#74533c", "img": "./assets/sofa/malabar/swatches/MB-814.jpg" },
      { "name": "SR 816", "code": "MB-816", "hex": "#8da19a", "img": "./assets/sofa/malabar/swatches/MB-816.jpg" },
      { "name": "SR 817", "code": "MB-817", "hex": "#b9ada2", "img": "./assets/sofa/malabar/swatches/MB-817.jpg" },
      { "name": "SR 818", "code": "MB-818", "hex": "#6f9690", "img": "./assets/sofa/malabar/swatches/MB-818.jpg" },
      { "name": "SR 821", "code": "MB-821", "hex": "#b6998f", "img": "./assets/sofa/malabar/swatches/MB-821.jpg" },
      { "name": "SR 822", "code": "MB-822", "hex": "#967d71", "img": "./assets/sofa/malabar/swatches/MB-822.jpg" },
      { "name": "SR 823", "code": "MB-823", "hex": "#a99e92", "img": "./assets/sofa/malabar/swatches/MB-823.jpg" }
    ]
  },
  {
    "id": "tribe",
    "name": "Tribe",
    "material": "Herringbone Weave",
    "category": "Sofa Upholstery",
    "tag": null,
    "composition": "100% Polyester",
    "rubLabel": "Rub Count",
    "rub": "40,000 Martindale",
    "gsm": 420,
    "care": "Machine washable up to 40°C. Do not bleach. Do not iron. Do not tumble dry. Professional dry cleaning (P – perchloroethylene solvent) permitted.",
    "application": "Sofa Upholstery",
    "widthCm": 140,
    "heroImage": "./assets/sofa/tribe/hero.jpg",
    "mrp": 788,
    "gstRate": 5,
    "hsnCode": "6005",
    "swatches": [
      { "name": "SR 03", "code": "TR-03", "hex": "#d0aa88", "img": "./assets/sofa/tribe/swatches/TR-03.jpg" },
      { "name": "SR 04", "code": "TR-04", "hex": "#d1a777", "img": "./assets/sofa/tribe/swatches/TR-04.jpg" },
      { "name": "SR 05", "code": "TR-05", "hex": "#a77c4c", "img": "./assets/sofa/tribe/swatches/TR-05.jpg" },
      { "name": "SR 07", "code": "TR-07", "hex": "#a48779", "img": "./assets/sofa/tribe/swatches/TR-07.jpg" },
      { "name": "SR 08", "code": "TR-08", "hex": "#785d4e", "img": "./assets/sofa/tribe/swatches/TR-08.jpg" },
      { "name": "SR 12", "code": "TR-12", "hex": "#755d62", "img": "./assets/sofa/tribe/swatches/TR-12.jpg" },
      { "name": "SR 13", "code": "TR-13", "hex": "#95a299", "img": "./assets/sofa/tribe/swatches/TR-13.jpg" },
      { "name": "SR 15", "code": "TR-15", "hex": "#688571", "img": "./assets/sofa/tribe/swatches/TR-15.jpg" },
      { "name": "SR 16", "code": "TR-16", "hex": "#346161", "img": "./assets/sofa/tribe/swatches/TR-16.jpg" },
      { "name": "SR 18", "code": "TR-18", "hex": "#465968", "img": "./assets/sofa/tribe/swatches/TR-18.jpg" },
      { "name": "SR 21", "code": "TR-21", "hex": "#827971", "img": "./assets/sofa/tribe/swatches/TR-21.jpg" },
      { "name": "SR 22", "code": "TR-22", "hex": "#5c534d", "img": "./assets/sofa/tribe/swatches/TR-22.jpg" }
    ]
  },
  {
    "id": "marsh",
    "name": "Marsh",
    "material": "Textured Weave",
    "category": "Sofa Upholstery",
    "tag": null,
    "composition": "100% Polyester",
    "rubLabel": "Rub Count",
    "rub": "50,000 Martindale",
    "gsm": 280,
    "application": "Sofa Upholstery, Curtains & Drapery",
    "heroImage": "./assets/sofa/marsh/hero.jpg",
    "widthCm": 140,
    "mrp": 440,
    "gstRate": 5,
    "hsnCode": "6005",
    "swatches": [
      { "name": "SR 1401", "code": "MA-1401", "hex": "#858075", "img": "./assets/sofa/marsh/swatches/MA-1401.jpg" },
      { "name": "SR 1402", "code": "MA-1402", "hex": "#6f6b67", "img": "./assets/sofa/marsh/swatches/MA-1402.jpg" },
      { "name": "SR 1403", "code": "MA-1403", "hex": "#8b7b61", "img": "./assets/sofa/marsh/swatches/MA-1403.jpg" },
      { "name": "SR 1404", "code": "MA-1404", "hex": "#907f64", "img": "./assets/sofa/marsh/swatches/MA-1404.jpg" },
      { "name": "SR 1405", "code": "MA-1405", "hex": "#9c8d73", "img": "./assets/sofa/marsh/swatches/MA-1405.jpg" },
      { "name": "SR 1406", "code": "MA-1406", "hex": "#7b6854", "img": "./assets/sofa/marsh/swatches/MA-1406.jpg" },
      { "name": "SR 1407", "code": "MA-1407", "hex": "#847667", "img": "./assets/sofa/marsh/swatches/MA-1407.jpg" },
      { "name": "SR 1408", "code": "MA-1408", "hex": "#66665e", "img": "./assets/sofa/marsh/swatches/MA-1408.jpg" },
      { "name": "SR 1409", "code": "MA-1409", "hex": "#9f5057", "img": "./assets/sofa/marsh/swatches/MA-1409.jpg" },
      { "name": "SR 1410", "code": "MA-1410", "hex": "#506f76", "img": "./assets/sofa/marsh/swatches/MA-1410.jpg" },
      { "name": "SR 1411", "code": "MA-1411", "hex": "#6e8185", "img": "./assets/sofa/marsh/swatches/MA-1411.jpg" },
      { "name": "SR 1412", "code": "MA-1412", "hex": "#88978d", "img": "./assets/sofa/marsh/swatches/MA-1412.jpg" },
      { "name": "SR 1413", "code": "MA-1413", "hex": "#738175", "img": "./assets/sofa/marsh/swatches/MA-1413.jpg" }
    ]
  },
  {
    "id": "cloud",
    "name": "Cloud",
    "material": "Textured Weave",
    "category": "Sofa Upholstery",
    "tag": null,
    "composition": "100% Polyester",
    "rubLabel": "Rub Count",
    "rub": "50,000 Martindale",
    "gsm": 280,
    "application": "Sofa Upholstery",
    "heroImage": "./assets/sofa/cloud/hero.jpg",
    "widthCm": 140,
    "mrp": 440,
    "gstRate": 5,
    "hsnCode": "6005",
    "swatches": [
      { "name": "SR 1501", "code": "CL-1501", "hex": "#c2bca1", "img": "./assets/sofa/cloud/swatches/CL-1501.jpg" },
      { "name": "SR 1502", "code": "CL-1502", "hex": "#b7b19b", "img": "./assets/sofa/cloud/swatches/CL-1502.jpg" },
      { "name": "SR 1503", "code": "CL-1503", "hex": "#a29c8a", "img": "./assets/sofa/cloud/swatches/CL-1503.jpg" },
      { "name": "SR 1504", "code": "CL-1504", "hex": "#948d7b", "img": "./assets/sofa/cloud/swatches/CL-1504.jpg" },
      { "name": "SR 1505", "code": "CL-1505", "hex": "#817464", "img": "./assets/sofa/cloud/swatches/CL-1505.jpg" },
      { "name": "SR 1506", "code": "CL-1506", "hex": "#83766f", "img": "./assets/sofa/cloud/swatches/CL-1506.jpg" },
      { "name": "SR 1507", "code": "CL-1507", "hex": "#769187", "img": "./assets/sofa/cloud/swatches/CL-1507.jpg" },
      { "name": "SR 1508", "code": "CL-1508", "hex": "#757960", "img": "./assets/sofa/cloud/swatches/CL-1508.jpg" },
      { "name": "SR 1509", "code": "CL-1509", "hex": "#5f756c", "img": "./assets/sofa/cloud/swatches/CL-1509.jpg" },
      { "name": "SR 1510", "code": "CL-1510", "hex": "#517e87", "img": "./assets/sofa/cloud/swatches/CL-1510.jpg" },
      { "name": "SR 1511", "code": "CL-1511", "hex": "#636b6f", "img": "./assets/sofa/cloud/swatches/CL-1511.jpg" },
      { "name": "SR 1512", "code": "CL-1512", "hex": "#777370", "img": "./assets/sofa/cloud/swatches/CL-1512.jpg" },
      { "name": "SR 1513", "code": "CL-1513", "hex": "#6f726d", "img": "./assets/sofa/cloud/swatches/CL-1513.jpg" },
      { "name": "SR 1514", "code": "CL-1514", "hex": "#636560", "img": "./assets/sofa/cloud/swatches/CL-1514.jpg" }
    ]
  }
];
